from flask import Blueprint
from .download_media.download_media_action import download_media_bp
from .load_more.load_more_action import load_more_bp
from .load_more_history.load_more_history_action import load_more_history_bp
from .mark_all_as_read.mark_all_as_read_action import mark_all_as_read_bp
from .mark_group_as_read.mark_group_as_read_action import mark_group_as_read_bp
from .set_max_items.set_max_items_action import set_max_items_bp
from .set_max_rendered_items.set_max_rendered_items_action import set_max_rendered_items_bp
from .set_no_text_mode.set_no_text_mode_action import set_no_text_mode_bp
from .set_scroll_as_read.set_scroll_as_read_action import set_scroll_as_read_bp
from .session_management.session_management_action import session_management_bp


actions_bp = Blueprint('actions', __name__, url_prefix='/actions')
actions_bp.register_blueprint(download_media_bp)
actions_bp.register_blueprint(load_more_bp)
actions_bp.register_blueprint(load_more_history_bp)
actions_bp.register_blueprint(mark_all_as_read_bp)
actions_bp.register_blueprint(mark_group_as_read_bp)
actions_bp.register_blueprint(set_max_items_bp)
actions_bp.register_blueprint(set_max_rendered_items_bp)
actions_bp.register_blueprint(set_no_text_mode_bp)
actions_bp.register_blueprint(set_scroll_as_read_bp)
actions_bp.register_blueprint(session_management_bp)
