name: galerie
services:
  # application
  galerie:
    image: ghcr.io/sekai-soft/galerie:latest
    container_name: galerie
    restart: unless-stopped
    environment:
      BASE_URL: 'https://galerie-reader.app'
      SQLALCHEMY_DATABASE_URI: 'postgresql://galerie:secret@postgres/galerie?sslmode=disable'
      MINIFLUX_BASE_URL: 'http://miniflux'
      NITTER_BASE_URL: 'http://nitter'
      MEDIA_PROXY_CUSTOM_URL: 'http://galerie-reader-media'
      Z2K2_BASE_URL: 'http://z2k2:8000'
      EYERIS_BASE_URL: 'http://eyeris:8000'
    env_file:
      - env
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=galerie
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=galerie
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run galerie
    env_file:
      - env
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # miniflux
  miniflux:
    image: miniflux/miniflux:2.2.12
    restart: unless-stopped
    depends_on:
      miniflux-postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@miniflux-postgres/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - PORT=80
      - BASE_URL=http://miniflux/
      - WORKER_POOL_SIZE=1
      - MEDIA_PROXY_CUSTOM_URL=http://galerie-reader-media
      - MEDIA_PROXY_RESOURCE_TYPES=image,audio,video
    env_file:
      - env
    ports:
      - "8080:80"
  miniflux-postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s

  # nitter
  nitter:
    image: ghcr.io/sekai-soft/nitter-pitchforked:v20250626
    # container_name: nitter
    # ports:
    #   - "127.0.0.1:8080:8080" # Replace with "8080:8080" if you don't use a reverse proxy
    volumes:
      - ./nitter.conf:/src/nitter.conf:Z,ro
      - ./sessions.jsonl:/src/sessions.jsonl:Z,ro # Run get_sessions.py to get the credentials
    depends_on:
      - nitter-redis
    restart: unless-stopped
    # healthcheck:
    #   test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 2
    user: "998:998"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
  nitter-redis:
    image: redis:6-alpine
    # container_name: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - nitter-pf-redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2
    user: "999:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

  # z2k2
  z2k2:
    image: ghcr.io/sekai-soft/z2k2:latest
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+psycopg2://z2k2:secret@z2k2-postgres:5432/z2k2
      - CACHE_TTL_SECONDS=3600
      - CACHE_TTL_JITTER_SECONDS=300
    ports:
      - "8081:8000"
    volumes:
      - ./sessions.jsonl:/app/sessions.jsonl
  z2k2-postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=z2k2
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=z2k2
    volumes:
      - z2k2-postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  # eyeris
  eyeris:
    image: ghcr.io/sekai-soft/eyeris:latest-arm64
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+psycopg2://eyeris:secret@eyeris-postgres:5432/eyeris
    ports:
      - "8082:8000"
  eyeris-postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=eyeris
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=eyeris
    volumes:
      - eyeris-postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres:
  miniflux-postgres:
  nitter-pf-redis:
  eyeris-postgres:
  z2k2-postgres:
