name: galerie
services:
  # application
  galerie:
    image: ghcr.io/sekai-soft/galerie:latest
    container_name: galerie
    restart: unless-stopped
    environment:
      BASE_URL: 'https://galerie-reader.app'
      SQLALCHEMY_DATABASE_URI: 'postgresql://galerie:secret@postgres/galerie?sslmode=disable'
      MINIFLUX_BASE_URL: 'http://miniflux'
      NITTER_BASE_URL: 'http://nitter'
      MEDIA_PROXY_CUSTOM_URL: 'http://galerie-reader-media'
    env_file:
      - env
    network_mode: service:galerie-ts
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=galerie
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=galerie
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  postgres-backup:
    image: ghcr.io/sekai-soft/postgres-backup-s3:15
    restart: unless-stopped
    env_file:
      - env-backup
      - /home/nixos/env-backup
    environment:
      S3_PREFIX: 'galerie'
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 7
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: galerie
      POSTGRES_USER: galerie
      POSTGRES_PASSWORD: secret
  galerie-ts:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: galerie
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:server
      - TS_STATE_DIR=/var/lib/tailscale
    env_file:
      - /home/nixos/env-tailscale
    volumes:
      - galerie-ts:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    labels:
      - com.centurylinklabs.watchtower.enable=true

  # miniflux
  miniflux:
    image: miniflux/miniflux:2.2.16
    restart: unless-stopped
    depends_on:
      miniflux-postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://miniflux:secret@miniflux-postgres/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1
      - CREATE_ADMIN=1
      - PORT=80
      - BASE_URL=http://miniflux/
      - WORKER_POOL_SIZE=1
      - MEDIA_PROXY_CUSTOM_URL=http://galerie-reader-media
      - MEDIA_PROXY_RESOURCE_TYPES=image,audio,video
    env_file:
      - env
    ports:
      - "8080:80"
  miniflux-postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - miniflux-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
  miniflux-postgres-backup:
    image: ghcr.io/sekai-soft/postgres-backup-s3:15
    restart: unless-stopped
    env_file:
      - env-backup-miniflux
      - /home/nixos/env-backup
    environment:
      S3_PREFIX: 'galerie-miniflux'
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 7
      POSTGRES_HOST: miniflux-postgres
      POSTGRES_DATABASE: miniflux
      POSTGRES_USER: miniflux
      POSTGRES_PASSWORD: secret

  # nitter
  nitter:
    image: ghcr.io/sekai-soft/nitter-pitchforked:v20260201
    # container_name: nitter
    # ports:
    #   - "127.0.0.1:8080:8080" # Replace with "8080:8080" if you don't use a reverse proxy
    volumes:
      - ./nitter.conf:/src/nitter.conf:Z,ro
      - ./sessions_cookies.jsonl:/src/sessions.jsonl:Z,ro
    depends_on:
      - nitter-redis
    restart: unless-stopped
    # healthcheck:
    #   test: wget -nv --tries=1 --spider http://127.0.0.1:8080/Jack/status/20 || exit 1
    #   interval: 30s
    #   timeout: 5s
    #   retries: 2
    user: "998:998"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
  nitter-redis:
    image: redis:6-alpine
    # container_name: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - nitter-pf-redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 5s
      retries: 2
    user: "999:1000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL

volumes:
  galerie-ts:
  postgres:
  miniflux-postgres:
  nitter-pf-redis:
