name: galerie
services:
  galerie:
    image: ghcr.io/sekai-soft/galerie:latest
    container_name: galerie
    restart: unless-stopped
    environment:
      BASE_URL: 'https://galerie-reader.app'
    env_file:
      - env
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run galerie
    env_file:
      - env
